name: MyTokens
main: com.toyz.MyTokens.MyTokens
version: 1.8
author: Toyz
description: A Token Plugin to give players a token style item within the server
commands:
  mytokens:
    description: Show all commands for mytokens
    aliases: [tokensadmin]
  myt:
    description: Show all user based commands for MyTokens
    aliases: [tokens]
    
permissions:
  #Sign Stuff
  mytokens.sign.place:
    description: Place a Token shop sign
    default: op
  mytokens.sign.use:
    description: Use a Token shop sign
    default: op

  #admin commands permissions
  mytokens.admin.reload:
    description: Reload the plugin
    default: op
  mytokens.admin.give:
    description: Gives a player tokens
    default: op
  mytokens.admin.take:
    description: Takes tokens from a player
    default: op
  mytokens.admin.reset:
    description: Resets a user to 0 tokens
    default: op
  mytokens.admin.enableblocks:
    description: Allows a user to disable certain blocks from dropping items
    default: op
  mytokens.admin.nopay:
    description: Allows staff to bypass shop price
    default: op
  mytokens.admin.userbal:
    description: Allows you to view another users balance
    default: op

  #public commands permissions
  mytokens.myt.open:
    description: Allows player to open the shop
    default: true
  mytokens.myt.bal:
    description: Allows user to see there balance
    default: true
  mytokens.myt.breakable:
    description: Allows user to see what blocks are breakable
    default: true
  mytokens.myt.give:
    description: Allows players to trade tokens
    default: op
  mytokens.myt.help:
    description: Allows players to see the MYT Command help
    default: op